baseurl = "/"
title = "Julia"

languagecode = "en"
defaultcontentlanguage = "en"

buildFuture = true
footnotereturnlinkcontents = "â†©"
relativeURLs = true

enableEmoji = true

paginate = 20
canonifyurls = true

ignoreFiles = [ "\\.qmd$", "\\.ipynb$" ]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"
  [markup.tableOfContents]
    endLevel = 1
    ordered = false
    startLevel = 1

[params]
  repourl = "https://github.com/WestGrid/julia"
  sfuavatar = "/img/sfu.png"
  dracavatar = "/img/drac.png"
  siteavatar = "/img/julia.png"
  error = "/img/404.png"
  favicon_32 = "/img/sfu_favicon.png"
  hidecredits = false
  hidecopyright = false
  summerschool2020url = "https://wgschool.netlify.app/julia/"
  autumnschool2020url = "https://autumnschool.netlify.app/julia/"
  modules2021url = "https://wgtm21.netlify.app/programming_julia/"
  since = 2020
  rtl = false
  math = true
  [params.utteranc]
    repo = "WestGrid/julia"
    issueTerm = "url"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
  name = "Github"
  icon = "fab fa-github fa-2x"
  weight = 3
  url = "https://github.com/WestGrid"
[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter fa-2x"
  weight = 4
  url = "https://twitter.com/WestGrid"
[[params.social]]
  name = "YouTube"
  icon = "fab fa-youtube fa-2x"
  weight = 5
  url = "https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw"
[[params.social]]
  name = "Events"
  icon = "fa fa-calendar-alt fa-2x"
  weight = 6
  url = "https://westgrid.github.io/trainingMaterials/blog/"

[[menu.main]]
  name = "Workshops"
  weight = 1
  url  = "workshops/"
[[menu.main]]
  name = "Webinars"
  weight = 2
  url  = "webinars/"
[[menu.main]]
  name = "Courses"
  weight = 3
  url  = "courses/"
[[menu.main]]
  name = "ðŸ“š"
  weight = 4
  url  = "https://westgrid.github.io/trainingMaterials/"
[[menu.main]]
  name = "ðŸ“¬"
  weight = 5
  url  = "mailto:rc-training@sfu.ca"
